- name: Check nginx configuration
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: Check if project files exist
  stat:
    path: "{{ project_conf_dir }}/live/{{ server_name }}"
  register: project

- name: Copy nginx project conf
  template:
    src: templates/nginx-certbot.conf
    dest: "{{ nginx_conf_dir }}/{{ server_name }}.conf"
  when: not project.stat.exists

- name: Start nginx container
  docker_container:
    name: ng01
    image: "{{ nginx_image }}"
    ports:
    - 80:80
    volumes:
    - "{{ nginx_conf_dir }}/:/etc/nginx/conf.d/:ro"
    - "{{ project_conf_dir }}/:/etc/letsencrypt/"
    - "{{ project_conf_dir }}/www/:/var/"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"
  when: not project.stat.exists

- name: Waiting for nginx containers
  pause:
    seconds: 3
  when: not project.stat.exists

- name: Issue certificate 
  docker_container:
    name: "{{ project_hostname }}"
    image: "{{ project_image }}"
    volumes:
    - "{{ project_conf_dir }}/:/etc/letsencrypt/"
    - "{{ project_conf_dir }}/:/var//"
    command: 
  when: not project.stat.exists

- name: Wait for certificate request
  pause:
    seconds: 3
  when: not project.stat.exists

- name: Copy nginx ssl conf
  template:
    src: templates/nginx-ssl.conf
    dest: "{{ nginx_conf_dir }}/{{ server_name }}.conf"
  notify: Restart nginx container 

- name: Copy nginx ssl param conf
  copy:
    src: "{{ item }}"
    dest: "{{ project_conf_dir }}/"
  with_items:
    - files/options-ssl-nginx.conf
    - files/ssl-dhparams.pem

- name: Start nginx containers 
  docker_container:
    name: ng01
    image: nginx:latest
    ports:
    - 80:80
    - 443:443
    - 9200:9200
    volumes:
    - "{{ nginx_conf_dir }}/:/etc/nginx/conf.d/:ro"
    - "{{ project_conf_dir }}/:/etc/letsencrypt/"
    - "{{ project_conf_dir }}//:/var/"
    networks:
    - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"